### ISSUE TITLE
Selection doesn't work on safari

### ISSUE THREAD

**Issue by zkirby** [Dan503/time-input-polyfill#3] opened 2019-07-15 21:50 UTC
Hi Dan!

It appears that `prevent_user_select` also prevents selection highlighting from working in Safari, I was wondering the reasoning behind this function?

Thanks!

**Comment by Dan503** [comment] 2019-07-15 22:29
In order to make the polyfill work I need to control what the user is able to select. Only day, month, **or** year is allowed to be selected at any one time.

Allowing the user to select any text in the input that they want causes bugs and breaks the functionality.

I'm unable to test in Safari since I only have access to a Windows PC. Does this functionality make the polyfill not work as intended?

**Comment by zkirby** [comment] 2019-07-15 23:18
I believe removing the prevent_user_select (or at least using = 'text' instead) doesn't prevent the functionality you mentioned. Or at least I can't seem to replicate said errors. 

And correct, in safari this prevents highlighting

**Comment by Dan503** [comment] 2019-07-16 00:47
It's been quite a while since I looked at the code for this. I might have a look tonight and see if I can remove it safely.

**Comment by zkirby** [comment] 2019-07-16 05:21
Awesome, thank you so much Dan, I appreciate you taking the time to go back and look through this :)!

**Comment by Dan503** [comment] 2019-07-16 12:05
I was fortunately able to replicate the sort of issues that you were describing in FireFox in the demo site. You were right, preventing user select was a pointless extra bit of functionality that was making the UX worse for no good reason. Thanks for pointing that out 😊👍

I've released a fix for this in version 1.0.6.

**Closed as completed by Dan503** 2019-07-16 12:05 UTC

**Comment by zkirby** [comment] 2019-07-16 16:29
Awesome, thanks for the quick response and fix!!
